# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56e36cac0e78fbb5aa603c64aeb8bc740358e9a0d775e8bba0eda08aa137dba75864725ac4ba5875b3cbe24d8502a1b152308b4564742e699c401ffb2daf1e56

test:
  secret_key_base: 7688a36502e9474679b9b2d5b7b3c06ab19cbb90d4b306276286c131be047742c2417290761a622bd2c117999780737a630ce45073be4433b520a8449538fd33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
